name: mo433
channels:
  - bottler
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - adwaita-icon-theme=48.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.6.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - at-spi2-atk=2.34.2
  - at-spi2-core=2.36.0
  - atk-1.0=2.36.0
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - black=25.1.0
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - catalogue=2.0.10
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.2.1
  - cloudpathlib=0.21.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.5
  - contourpy=1.3.1
  - cpuonly=2.0
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cycler=0.11.0
  - cymem=2.0.11
  - cyrus-sasl=2.1.28
  - cython-blis=1.0.1
  - dataclasses=0.8
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - epoxy=1.5.4
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=4.4.0
  - filelock=3.17.0
  - flake8=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - fvcore=0.1.5.post20221221
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - gobject-introspection=1.84.0
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gtk2=2.24.33
  - gtk3=3.24.21
  - gts=0.7.6
  - h11=0.16.0
  - harfbuzz=10.2.0
  - hicolor-icon-theme=0.17
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - imageio=2.37.0
  - intel-openmp=2025.0.0
  - iopath=0.1.10
  - ipykernel=6.30.1
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - lame=3.100
  - langcodes=3.5.0
  - language-data=1.3.0
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.8.1
  - libavif=1.1.1
  - libboost=1.88.0
  - libcst=1.6.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.15.0
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.4
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - librsvg=2.56.3
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.20.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libtool=2.4.7
  - libunistring=1.3
  - libuuid=2.41.1
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - llvmlite=0.44.0
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - marisa-trie=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mesalib=25.1.5
  - mistune=3.1.2
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - moreorless=0.5.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - murmurhash=1.0.12
  - mypy_extensions=1.0.0
  - mysql=9.3.0
  - mysql-client=9.3.0
  - mysql-common=9.3.0
  - mysql-devel=9.3.0
  - mysql-libs=9.3.0
  - mysql-server=9.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.5
  - ninja=1.12.1
  - ninja-base=1.12.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.89.1
  - numba=0.61.2
  - numexpr=2.11.0
  - numpy-base=2.2.5
  - nvidiacub=1.10.0
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.2
  - overrides=7.4.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.1
  - pango=1.50.7
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - ply=3.11
  - poppler=24.09.0
  - poppler-data=0.4.11
  - portalocker=3.0.0
  - preshed=3.0.9
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycodestyle=2.12.1
  - pycparser=2.23
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydot=4.0.1
  - pydotplus=2.0.2
  - pyflakes=3.2.0
  - pyglet=2.1.8
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyopengl=3.1.9
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-graphviz=0.16
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.1
  - qtsvg=6.9.2
  - qttools=6.9.1
  - qtwayland=6.9.1
  - qtwebchannel=6.9.1
  - qtwebsockets=6.9.1
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scipy=1.16.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=72.1.0
  - shellingham=1.5.0
  - sip=6.12.0
  - six=1.17.0
  - smart_open=7.3.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - srsly=2.5.1
  - stack_data=0.6.3
  - stdlibs=2025.5.10
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - termcolor=2.1.0
  - terminado=0.18.1
  - tesseract=5.2.0
  - thinc=8.3.2
  - threadpoolctl=3.5.0
  - tifffile=2025.2.18
  - tinycss2=1.4.0
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.2.1
  - torchview=0.2.6
  - tornado=6.5.1
  - tqdm=4.67.1
  - trailrunner=1.4.0
  - traitlets=5.14.3
  - typer=0.9.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - umap-learn=0.5.9.post2
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - usort=1.0.8.post1
  - wasabi=1.1.3
  - wayland=1.24.0
  - wcwidth=0.2.13
  - weasel=0.4.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - wurlitzer=3.1.1
  - x264=1!161.3030
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - argparse==1.4.0
      - arrow==1.3.0
      - astroid==3.3.11
      - asyncssh==2.21.0
      - atomicwrites==1.4.1
      - autopep8==2.0.4
      - batchgenerators==0.25.1
      - bcrypt==4.3.0
      - beartype==0.21.0
      - binaryornot==0.4.4
      - cfgv==3.4.0
      - chardet==5.2.0
      - cookiecutter==2.6.0
      - cryptography==45.0.7
      - deepdiff==8.6.1
      - deprecated==1.2.18
      - diff-match-patch==20241021
      - dill==0.4.0
      - distlib==0.4.0
      - docstring-to-markdown==0.17
      - docutils==0.21.2
      - einops==0.8.1
      - fastcore==1.8.8
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - humanize==4.13.0
      - icecream==2.1.8
      - identify==2.6.14
      - imagesize==1.4.1
      - imgaug==0.4.0
      - importlib-metadata==8.7.0
      - inflection==0.5.1
      - intervaltree==3.1.0
      - ipython==8.37.0
      - isort==6.0.1
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jeepney==0.9.0
      - jellyfish==1.2.0
      - jsonlines==4.0.0
      - keyring==25.6.0
      - levenshtein==0.27.1
      - linecache2==1.0.0
      - loguru==0.7.3
      - lovely-numpy==0.2.13
      - lovely-tensors==0.1.18
      - mergedeep==1.3.4
      - more-itertools==10.8.0
      - multidict==6.6.4
      - nibabel==5.3.2
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numpy==2.2.6
      - numpydoc==1.9.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - orderly-set==5.5.0
      - pickleshare==0.7.5
      - pluggy==1.6.0
      - plum-dispatch==2.5.7
      - pre-commit==4.3.0
      - propcache==0.3.2
      - pydocstyle==6.3.0
      - pygithub==2.8.1
      - pyjwt==2.10.1
      - pylint==3.3.8
      - pylint-venv==3.0.4
      - pyls-spyder==0.4.0
      - pynacl==1.6.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.17
      - python-levenshtein==0.27.1
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-server==1.12.2
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pyuca==1.2
      - pyxdg==0.28
      - qdarkstyle==3.2.3
      - qstylizer==0.2.4
      - qtawesome==1.4.0
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - random2==1.0.2
      - rapidfuzz==3.14.1
      - regex==2025.9.1
      - roman-numerals-py==3.1.0
      - rope==1.14.0
      - rtree==1.4.1
      - secretstorage==3.4.0
      - shapely==2.1.1
      - simpleitk==2.5.2
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - spyder==6.0.8
      - spyder-kernels==3.0.5
      - superqt==0.7.6
      - text-unidecode==1.3
      - textdistance==4.6.3
      - three-merge==0.1.1
      - tomlkit==0.13.3
      - torch==2.2.2
      - torch-snippets==0.560
      - torch-summary==1.4.5
      - torchaudio==2.8.0
      - torchio==0.20.22
      - torchvision==0.23.0+cu126
      - traceback2==1.4.0
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20250822
      - typing==3.7.4.3
      - ujson==5.11.0
      - unittest2==1.1.0
      - virtualenv==20.34.0
      - watchdog==6.0.0
      - whatthepatch==1.0.7
      - xmltodict==1.0.0
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.23.0
